apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 10
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: httpd:alpine3.19
          name: httpd
  strategy:
    type: RollingUpdate # Default type if not declared
    rollingUpdate:
      maxUnavailable: 1 # Accepts integers or percentages
      maxSurge: 1 # Same as above
