#!/bin/bash

# Description: Check if argument is a file or directory


if [[ -z "$1" || "$1" == "--help" ]]; then
    # Provide help statement to user
    echo "Usage: $0 <filename>"
    exit 1
fi


if [[ -f "$1" && -x "$1" ]]; then
    echo "File exists and it's an executable"
elif [[ -f "$1" && -r "$1" ]]; then
    echo "File exists and it's readable"
elif [[ -d "$1" ]]; then
    echo "It's a directory"
else
    echo "Not Found: $1"
fi
