#!/bin/bash

# Description: Using case for conditional checking
# Longer than 2-3 if conditions should use case

case $1 in
    start)
        echo "Starting service..."
        ;;
    stop)
        echo "Stopping service..."
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
